---
- name: gather facts from sandbox
  hosts: sandbox
  gather_facts: false

  tasks:

  - name: Gather cisco ios facts
    cisco.ios.ios_facts:
      gather_subset: config
      gather_network_resources: "{{ network_resource | default('!vlans,!snmp_server') }}"