---
- name: get and display interface status
  hosts: sandbox
  gather_facts: false

  tasks:

  - name: get L3 interface status
    cisco.ios.ios_command:
      commands: show ip interface brief
    register: output

  - name: display interface status 
    debug:
      msg: "{{ output.stdout_lines }}"
