---
- name: gather facts from sandbox
  hosts: sandbox
  gather_facts: false

  tasks:

  - name: gather facts
    cisco.ios.ios_facts:
    register: output

  - debug:
      msg:
        - "hostname: {{ ansible_net_hostname }}"
        - "version: {{ ansible_net_version }}"
        - "hardware: {{ ansible_net_model }}"
        - "serial no: {{ ansible_net_serialnum }}"

